### ISSUE TITLE
Allow users to run Chroma from arbitrary subdirectory of project

### ISSUE THREAD

**Issue by generic-github-user** [codeinred/chroma#2]
Quoted from @codeinred:

> If there’s no chroma.toml in the current directory, it should search through parent directories searching for a chroma.toml, and once it finds one, changes the working directory to that directory. This should be done on startup

**Comment by codeinred** [comment]
Hi! I'm really sorry, I just saw you assigned this to yourself. I implemented this in 5899e3047a777ec87d95995d522754177771f35c but I'll try to be careful not to do things you were already working on in the future!

**Comment by generic-github-user** [comment]
Don't worry about it, glad you were able to get this done! I hadn't actually gotten a chance to start working on it but it looks like you did a nice job.
